### ISSUE TITLE
A secret key is required to use CSRF

### ISSUE THREAD

**Issue by FernandoGarcia** [app-generator/flask-dashboard-adminlte#4]
Hi!

I'm getting this error:

```
File "/home/fernandogarcia/Downloads/flask-dashboard-adminlte/env/lib/python3.6/site-packages/flask_wtf/csrf.py", line 128, in _get_config
    raise RuntimeError(message)
RuntimeError: A secret key is required to use CSRF
```
Looks like this piece of code is not being used or CSRF key is something else.

`SECRET_KEY = config('SECRET_KEY', default='S#perS3crEt_007')`

The server is always returning HTTP 500.

![flask](https://user-images.githubusercontent.com/2778501/124200892-da803f00-daac-11eb-9c18-73e05dbcc7e5.png)

Can you help me please?

Best regards.

**Comment by app-generator** [comment]
Hello @FernandoGarcia, 

Thank you for using our product.
This error reported quite often by our users happens when the  `FLASK_APP` is not exported. 
Make sure you have this variable properly set up in the environment.

- For Linux/MacOS:
`export FLASK_APP=run.py`
- For Windows - cmd 
`set FLASK_APP=run.py`
- For Windows - power shell
`$env:FLASK_APP = ".\run.py"`

If the problem persists, please reply with more information regarding your environment and runtime:
- OS type
- Python Version
- A full runtime log

**Comment by FernandoGarcia** [comment]
Hi!

It worked now.

I'm using Ubuntu 18.04  over WSL.

I think I have used `set FLASK_APP=run.py` instead `export FLASK_APP=run.py`  maybe a distraction because I was getting in trouble to run `virtualenv env` command.

In case someone is getting `command not found` while using `virtualenv env`  the solution is export the path using this command.

`export PATH="${PATH}:$(python3 -c 'import site; print(site.USER_BASE)')/bin"\`

Thanks for your help!

Best regards.

**Comment by app-generator** [comment]
Happy coding!
